/**
 * eff-yaml CLI の本体。
 * 入出力を注入できるよう run() に切り出し、プロセスへの接続は bin.ts が行う。
 */
import { parseArgs } from 'node:util';
import { readFile, writeFile } from 'node:fs/promises';
import { parse } from 'yaml';
import { evaluateYaml, renderPreserving, type Value } from './index.js';

export interface CliIo {
  stdin: AsyncIterable<Buffer | string>;
  stdout: (text: string) => void;
  stderr: (text: string) => void;
}

const USAGE = `\
Usage: eff-yaml [file] [-p name=value]... [-o file] [--check]

effectful-yaml 文書を評価し、結果を YAML で標準出力に書く。
$std.log の中身は標準エラー出力に書く。

  file             入力ファイル。省略時と "-" は標準入力。
  -p, --param      起動時パラメータ。値は YAML として解釈する。繰り返し可。
  -o, --output     結果の書き出し先ファイル。省略時は標準出力。
  --check          -o と併用し、出力先が最新か検査する（書き込まない）。
  -h, --help       このヘルプ。
`;

function buildHeader(file: string | undefined, params: string[]): string {
  const from = file === undefined || file === '-' ? '' : ` from ${file}`;
  const withParams = params.map((p) => ` -p ${p}`).join('');
  return `# Code generated by eff-yaml${from}${withParams}; DO NOT EDIT.\n`;
}

function buildRegenerateCommand(file: string | undefined, params: string[], output: string): string {
  const target = file === undefined ? '' : ` ${file}`;
  const withParams = params.map((p) => ` -p ${p}`).join('');
  return `eff-yaml${target}${withParams} -o ${output}`;
}

function toLines(text: string): string[] {
  return (text.endsWith('\n') ? text.slice(0, -1) : text).split('\n');
}

type DiffOp = { kind: ' ' | '-' | '+'; line: string };

// ponytail: O(n²) の行 LCS。設定ファイル規模なら十分、巨大文書で問題になったら Myers に差し替える
function diffLines(a: string[], b: string[]): string[] {
  const n = a.length;
  const m = b.length;
  const lcs: number[][] = Array.from({ length: n + 1 }, () => new Array<number>(m + 1).fill(0));
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      lcs[i]![j] = a[i] === b[j] ? lcs[i + 1]![j + 1]! + 1 : Math.max(lcs[i + 1]![j]!, lcs[i]![j + 1]!);
    }
  }
  const ops: DiffOp[] = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i] === b[j]) {
      ops.push({ kind: ' ', line: a[i]! });
      i++;
      j++;
    } else if (lcs[i + 1]![j]! >= lcs[i]![j + 1]!) {
      ops.push({ kind: '-', line: a[i]! });
      i++;
    } else {
      ops.push({ kind: '+', line: b[j]! });
      j++;
    }
  }
  while (i < n) ops.push({ kind: '-', line: a[i++]! });
  while (j < m) ops.push({ kind: '+', line: b[j++]! });
  return formatHunks(ops);
}

const DIFF_CONTEXT = 2;

function formatHunks(ops: DiffOp[]): string[] {
  const changed = ops.reduce<number[]>((acc, op, idx) => {
    if (op.kind !== ' ') acc.push(idx);
    return acc;
  }, []);
  if (changed.length === 0) return [];
  const clusters: Array<[number, number]> = [];
  let start = changed[0]!;
  let end = changed[0]!;
  for (const idx of changed.slice(1)) {
    if (idx - end <= DIFF_CONTEXT * 2 + 1) {
      end = idx;
    } else {
      clusters.push([start, end]);
      start = idx;
      end = idx;
    }
  }
  clusters.push([start, end]);

  const out: string[] = [];
  clusters.forEach(([cs, ce], k) => {
    if (k > 0) out.push('...');
    const from = Math.max(0, cs - DIFF_CONTEXT);
    const to = Math.min(ops.length - 1, ce + DIFF_CONTEXT);
    for (let idx = from; idx <= to; idx++) out.push(`${ops[idx]!.kind}${ops[idx]!.line}`);
  });
  return out;
}

async function checkOutput(
  outFile: string,
  expected: string,
  file: string | undefined,
  params: string[],
  io: CliIo,
): Promise<number> {
  const regenCmd = buildRegenerateCommand(file, params, outFile);
  let existing: Buffer;
  try {
    existing = await readFile(outFile);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') {
      io.stderr(`eff-yaml: ${outFile} がない。次のコマンドで再生成する:\n  ${regenCmd}\n`);
      return 1;
    }
    throw e;
  }
  if (existing.equals(Buffer.from(expected, 'utf8'))) return 0;
  const diff = diffLines(toLines(existing.toString('utf8')), toLines(expected)).join('\n');
  io.stderr(`eff-yaml: ${outFile} が最新ではない。次のコマンドで再生成する:\n  ${regenCmd}\n\n${diff}\n`);
  return 1;
}

function logLine(v: Value): string {
  return typeof v === 'string' ? v : (JSON.stringify(v) ?? String(v));
}

function parseParams(pairs: string[]): Record<string, Value> {
  const params: Record<string, Value> = {};
  for (const pair of pairs) {
    const eq = pair.indexOf('=');
    if (eq <= 0) throw new Error(`--param には name=value の形を渡す: ${pair}`);
    params[pair.slice(0, eq)] = parse(pair.slice(eq + 1)) as Value;
  }
  return params;
}

async function readAll(stream: AsyncIterable<Buffer | string>): Promise<string> {
  let source = '';
  for await (const chunk of stream) source += chunk;
  return source;
}

export async function run(argv: string[], io: CliIo): Promise<number> {
  try {
    const { values, positionals } = parseArgs({
      args: argv,
      allowPositionals: true,
      options: {
        param: { type: 'string', short: 'p', multiple: true },
        output: { type: 'string', short: 'o' },
        check: { type: 'boolean' },
        help: { type: 'boolean', short: 'h' },
      },
    });
    if (values.help) {
      io.stdout(USAGE);
      return 0;
    }
    if (values.check && values.output === undefined) {
      throw new Error('--check には -o の指定が要る');
    }
    if (positionals.length > 1) throw new Error(`入力ファイルは一つだけ指定できる: ${positionals.join(', ')}`);
    const file = positionals[0];
    const source = file === undefined || file === '-' ? await readAll(io.stdin) : await readFile(file, 'utf8');
    const value = await evaluateYaml(source, {
      params: parseParams(values.param ?? []),
      onLog: (v) => io.stderr(logLine(v) + '\n'),
    });
    const rendered = renderPreserving(source, value);
    if (values.output === undefined) {
      io.stdout(rendered);
      return 0;
    }
    const expected = buildHeader(file, values.param ?? []) + rendered;
    if (values.check) {
      return await checkOutput(values.output, expected, file, values.param ?? [], io);
    }
    await writeFile(values.output, expected);
    return 0;
  } catch (e) {
    io.stderr(`eff-yaml: ${e instanceof Error ? e.message : String(e)}\n`);
    return 1;
  }
}
